version: "3.7"

services:
  order:
    build:
      context: .
    working_dir: /opt/shop-services/services/order
    command: nodemon app.js
    volumes:
      - type: bind
        source: ./services
        target: /opt/shop-services/services
    environment:
      - ORDER_SERVICE_PORT=8001
      - ACCESS_SERVICE_HOST=access
      - ACCESS_SERVICE_PORT=8002
      - INVENTORY_SERVICE_HOST=inventory
      - INVENTORY_SERVICE_PORT=8003
      - PAYMENT_SERVICE_HOST=payment
      - PAYMENT_SERVICE_PORT=8004
      - SHIPPING_SERVICE_HOST=shipping
      - SHIPPING_SERVICE_PORT=8005
      - JAEGER_HOST=jaeger
      - JAEGER_PORT=6832
      - DD_AGENT_HOST=ddagent
      - DD_AGENT_TRACING_PORT=8126
      - DD_API_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_XRAY_DAEMON_HOST=awsxraydaemon
      - AWS_XRAY_DAEMON_PORT=2000
      - SENTRY_DSN
      - SPLUNK_HOST=splunk
      - SPLUNK_PORT=8088
      - SPLUNK_TOKEN
    ports:
      - '8001:8001'

  access:
    build:
      context: .
    working_dir: /opt/shop-services/services/access
    command: nodemon app.js
    volumes:
      - type: bind
        source: ./services
        target: /opt/shop-services/services
    environment:
      - ACCESS_SERVICE_PORT=8002
      - JAEGER_HOST=jaeger
      - JAEGER_PORT=6832
      - DD_AGENT_HOST=ddagent
      - DD_AGENT_TRACING_PORT=8126
      - DD_API_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_XRAY_DAEMON_HOST=awsxraydaemon
      - AWS_XRAY_DAEMON_PORT=2000
    ports:
      - '8002:8002'

  inventory:
    build:
      context: .
    working_dir: /opt/shop-services/services/inventory
    command: nodemon app.js
    volumes:
      - type: bind
        source: ./services
        target: /opt/shop-services/services
    environment:
      - INVENTORY_SERVICE_PORT=8003
      - ACCESS_SERVICE_HOST=access
      - ACCESS_SERVICE_PORT=8002
      - JAEGER_HOST=jaeger
      - JAEGER_PORT=6832
      - DD_AGENT_HOST=ddagent
      - DD_AGENT_TRACING_PORT=8126
      - DD_API_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_XRAY_DAEMON_HOST=awsxraydaemon
      - AWS_XRAY_DAEMON_PORT=2000
    ports:
      - '8003:8003'

  payment:
    build:
      context: .
    working_dir: /opt/shop-services/services/payment
    command: nodemon app.js
    volumes:
      - type: bind
        source: ./services
        target: /opt/shop-services/services
    environment:
      - PAYMENT_SERVICE_PORT=8004
      - ACCESS_SERVICE_HOST=access
      - ACCESS_SERVICE_PORT=8002
      - JAEGER_HOST=jaeger
      - JAEGER_PORT=6832
      - DD_AGENT_HOST=ddagent
      - DD_AGENT_TRACING_PORT=8126
      - DD_API_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_XRAY_DAEMON_HOST=awsxraydaemon
      - AWS_XRAY_DAEMON_PORT=2000
    ports:
      - '8004:8004'

  shipping:
    build:
      context: .
    working_dir: /opt/shop-services/services/shipping
    command: nodemon app.js
    volumes:
      - type: bind
        source: ./services
        target: /opt/shop-services/services
    environment:
      - SHIPPING_SERVICE_PORT=8005
      - ACCESS_SERVICE_HOST=access
      - ACCESS_SERVICE_PORT=8002
      - JAEGER_HOST=jaeger
      - JAEGER_PORT=6832
      - DD_AGENT_HOST=ddagent
      - DD_AGENT_TRACING_PORT=8126
      - DD_API_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_XRAY_DAEMON_HOST=awsxraydaemon
      - AWS_XRAY_DAEMON_PORT=2000
    ports:
      - '8005:8005'

  jaeger:
    image: jaegertracing/all-in-one:1.8
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686'
      - '14268:14268'
      - '9411:9411'

  ddagent:
    image: datadog/docker-dd-agent
    environment:
      - DD_API_KEY
      - DD_APM_ENABLED=true
    ports:
      - '8125:8125/tcp'
      - '8126:8126/tcp'

  redis:
    image: redis
    ports:
      - '6379:6379/tcp'

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    ports:
      - '5432:5432/tcp'

  # sentry:
  #   image: sentry
  #   environment:
  #     - SENTRY_SECRET_KEY
  #     - SENTRY_POSTGRES_HOST=postgres
  #     - SENTRY_POSTGRES_PORT=5432
  #     - SENTRY_DB_NAME=sentry
  #     - SENTRY_DB_USER
  #     - SENTRY_DB_PASSWORD
  #     - SENTRY_REDIS_HOST=redis
  #     - SENTRY_REDIS_PORT=6379
  #     - SENTRY_REDIS_DB=0
  #     - SENTRY_EMAIL_HOST=mailcatcher
  #     - SENTRY_EMAIL_PORT=1025
  #   ports:
  #     - '8089:9000'

  # sentrycron:
  #   image: sentry
  #   command: sentry run cron
  #   environment:
  #     - SENTRY_SECRET_KEY
  #     - SENTRY_POSTGRES_HOST=postgres
  #     - SENTRY_POSTGRES_PORT=5432
  #     - SENTRY_DB_NAME=sentry
  #     - SENTRY_DB_USER
  #     - SENTRY_DB_PASSWORD
  #     - SENTRY_REDIS_HOST=redis
  #     - SENTRY_REDIS_PORT=6379
  #     - SENTRY_REDIS_DB=0
  #     - SENTRY_EMAIL_HOST=mailcatcher
  #     - SENTRY_EMAIL_PORT=1025

  # sentryworker:
  #   image: sentry
  #   command: sentry run worker
  #   environment:
  #     - SENTRY_SECRET_KEY
  #     - SENTRY_POSTGRES_HOST=postgres
  #     - SENTRY_POSTGRES_PORT=5432
  #     - SENTRY_DB_NAME=sentry
  #     - SENTRY_DB_USER
  #     - SENTRY_DB_PASSWORD
  #     - SENTRY_REDIS_HOST=redis
  #     - SENTRY_REDIS_PORT=6379
  #     - SENTRY_REDIS_DB=0
  #     - SENTRY_EMAIL_HOST=mailcatcher
  #     - SENTRY_EMAIL_PORT=1025

  mailcatcher:
    build:
      context: mailcatcher
    command: mailcatcher --http-ip 0.0.0.0 && tail -f /dev/null
    ports:
      - '1080:1080'
      - '1025:1025'

  splunk:
    image: splunk/splunk
    environment:
      - SPLUNK_PASSWORD
      - SPLUNK_START_ARGS=--accept-license
    ports:
      - '8090:8000'
      - '8088:8088'

  awsxraydaemon:
    image: amazon/aws-xray-daemon
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
    ports:
      - '2000:2000'
